function Hd = filt2
%FILT2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 24-Feb-2015 22:16:38

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 32556;  % Sampling Frequency

N      = 100;   % Order
Fstop1 = 10;    % First Stopband Frequency
Fpass1 = 60;    % First Passband Frequency
Fpass2 = 500;   % Second Passband Frequency
Fstop2 = 600;   % Second Stopband Frequency
Wstop1 = 1;     % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 1000;  % Second Stopband Weight
dens   = 100;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
